version: "2"

services:
  app:
    build: dev/
    image: aws-s3-proxy:dev
    command: go run /go/src/github.com/pottava/aws-s3-proxy/main.go
    ports:
      - 8080:80
    volumes:
      - .:/go/src/github.com/pottava/aws-s3-proxy
    working_dir: /go/src/github.com/pottava/aws-s3-proxy
    environment:
      - AWS_REGION=ap-northeast-1
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_S3_BUCKET
      - AWS_S3_KEY_PREFIX
      - INDEX_DOCUMENT
      - DIRECTORY_LISTINGS
      - HTTP_CACHE_CONTROL
      - HTTP_EXPIRES
      - BASIC_AUTH_USER
      - BASIC_AUTH_PASS
      - SSL_CERT_PATH
      - SSL_KEY_PATH
      - CORS_ALLOW_ORIGIN
      - CORS_ALLOW_METHODS
      - CORS_ALLOW_HEADERS
      - CORS_MAX_AGE
      - ACCESS_LOG=true
      - CONTENT_ENCODING
    container_name: app
