version: "2.1"

services:
  app:
    image: golang:1.13.7-alpine3.11
    command: go run main.go
    ports:
      - 8080:80
    volumes:
      - $GOPATH:/go
      - .:/go/src/github.com/pottava/aws-s3-proxy
    working_dir: /go/src/github.com/pottava/aws-s3-proxy
    environment:
      - AWS_REGION=ap-northeast-1
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_S3_BUCKET
      - AWS_S3_KEY_PREFIX
      - INDEX_DOCUMENT
      - DIRECTORY_LISTINGS
      - DIRECTORY_LISTINGS_FORMAT
      - HTTP_CACHE_CONTROL
      - HTTP_EXPIRES
      - BASIC_AUTH_USER
      - BASIC_AUTH_PASS
      - SSL_CERT_PATH
      - SSL_KEY_PATH
      - CORS_ALLOW_ORIGIN
      - CORS_ALLOW_METHODS
      - CORS_ALLOW_HEADERS
      - CORS_MAX_AGE
      - ACCESS_LOG=true
      - CONTENT_ENCODING
      - HEALTHCHECK_PATH
      - GET_ALL_PAGES_IN_DIR=true
    container_name: app
